name: one-on-one

on:
  [push]

jobs:
  notes:
    name: create meeting notes
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
      
    - name: Create notes PR
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
