name: one-on-one

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  notes:
    name: create meeting notes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: sophshep/one-on-one/.github/actions/one-on-one
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
