name: one-on-one

on:
  [push]

jobs:
  notes:
    name: create meeting notes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            MEETING_DATE=$(date -d "+1 day" +%Y-%m-%d)
            PULL_REQUEST_TITLE="1:1 notes for $MEETING_DATE"
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: PULL_REQUEST_TITLE,
              head: `new-branch`,
              base: 'master',
              body: '👋 what is up bitches!'
            })
